version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - MALLOC_ARENA_MAX=4
      - refresh_rate=300s
      - logger.level=DEBUG
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  # kibana:
  #   container_name: kibana
  #   image: docker.elastic.co/kibana/kibana:7.4.0
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elasticsearch
  #   mem_limit: 1g

  backend:
    build: search-api
    depends_on:
      - elasticsearch
    restart: always
    volumes:
      - ./search-api:/app
    stdin_open: true  # enable attach for pdb
    tty: true
    ports:
      - "8080:80"
    mem_limit: 1g
    
  site:
    build: frontend-react
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend-react:/site
    ports:
      - "8090:80"

volumes:
  elasticsearch-data:
    driver: local
